# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{paraphraser}
  s.version = "1.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vinay Patel"]
  s.date = %q{2011-01-07}
  s.description = %q{Paraphraser, is a very simple gem.
It adds a rake task that will drop, re-create and migrate a database (default is test) and will output the sql generated in the migration process.
It will output the sql to screen as well as to a file ./migration.sql.
}
  s.email = %q{mail@vinayvinay.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/paraphraser.rb",
    "lib/paraphraser/convertor.rb",
    "lib/paraphraser/railtie.rb",
    "lib/paraphraser/railties/paraphraser.rake",
    "paraphraser.gemspec",
    "test/helper.rb",
    "test/test_paraphraser.rb"
  ]
  s.homepage = %q{http://github.com/vinayvinay/paraphraser}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{provides a rake task to convert migrations to sql statements for *the dba*.}
  s.test_files = [
    "test/helper.rb",
    "test/test_paraphraser.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

